language: r
r:
  - oldrel
  - release
  - devel

script:
- Rscript -e 'install.packages("devtools", repos = "http://cran.rstudio.com")'
- Rscript -e 'install.packages( "readr", repo = "https://cloud.r-project.org")'
- Rscript -e 'install.packages( "tidyverse", repo = "http://cran.rstudio.com")'
